package com.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TEmployeeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public TEmployeeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmployeeIdIsNull() {
			addCriterion("EMPLOYEE_ID is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNotNull() {
			addCriterion("EMPLOYEE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdEqualTo(Integer value) {
			addCriterion("EMPLOYEE_ID =", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotEqualTo(Integer value) {
			addCriterion("EMPLOYEE_ID <>", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThan(Integer value) {
			addCriterion("EMPLOYEE_ID >", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("EMPLOYEE_ID >=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThan(Integer value) {
			addCriterion("EMPLOYEE_ID <", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
			addCriterion("EMPLOYEE_ID <=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIn(List<Integer> values) {
			addCriterion("EMPLOYEE_ID in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotIn(List<Integer> values) {
			addCriterion("EMPLOYEE_ID not in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
			addCriterion("EMPLOYEE_ID between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("EMPLOYEE_ID not between", value1, value2,
					"employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameIsNull() {
			addCriterion("EMPLOYEE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameIsNotNull() {
			addCriterion("EMPLOYEE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameEqualTo(String value) {
			addCriterion("EMPLOYEE_NAME =", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameNotEqualTo(String value) {
			addCriterion("EMPLOYEE_NAME <>", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameGreaterThan(String value) {
			addCriterion("EMPLOYEE_NAME >", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameGreaterThanOrEqualTo(String value) {
			addCriterion("EMPLOYEE_NAME >=", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameLessThan(String value) {
			addCriterion("EMPLOYEE_NAME <", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameLessThanOrEqualTo(String value) {
			addCriterion("EMPLOYEE_NAME <=", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameLike(String value) {
			addCriterion("EMPLOYEE_NAME like", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameNotLike(String value) {
			addCriterion("EMPLOYEE_NAME not like", value, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameIn(List<String> values) {
			addCriterion("EMPLOYEE_NAME in", values, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameNotIn(List<String> values) {
			addCriterion("EMPLOYEE_NAME not in", values, "employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameBetween(String value1, String value2) {
			addCriterion("EMPLOYEE_NAME between", value1, value2,
					"employeeName");
			return (Criteria) this;
		}

		public Criteria andEmployeeNameNotBetween(String value1, String value2) {
			addCriterion("EMPLOYEE_NAME not between", value1, value2,
					"employeeName");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andRealNameIsNull() {
			addCriterion("REAL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andRealNameIsNotNull() {
			addCriterion("REAL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andRealNameEqualTo(String value) {
			addCriterion("REAL_NAME =", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotEqualTo(String value) {
			addCriterion("REAL_NAME <>", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameGreaterThan(String value) {
			addCriterion("REAL_NAME >", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameGreaterThanOrEqualTo(String value) {
			addCriterion("REAL_NAME >=", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameLessThan(String value) {
			addCriterion("REAL_NAME <", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameLessThanOrEqualTo(String value) {
			addCriterion("REAL_NAME <=", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameLike(String value) {
			addCriterion("REAL_NAME like", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotLike(String value) {
			addCriterion("REAL_NAME not like", value, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameIn(List<String> values) {
			addCriterion("REAL_NAME in", values, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotIn(List<String> values) {
			addCriterion("REAL_NAME not in", values, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameBetween(String value1, String value2) {
			addCriterion("REAL_NAME between", value1, value2, "realName");
			return (Criteria) this;
		}

		public Criteria andRealNameNotBetween(String value1, String value2) {
			addCriterion("REAL_NAME not between", value1, value2, "realName");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("SEX is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("SEX is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(String value) {
			addCriterion("SEX =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(String value) {
			addCriterion("SEX <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(String value) {
			addCriterion("SEX >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(String value) {
			addCriterion("SEX >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(String value) {
			addCriterion("SEX <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(String value) {
			addCriterion("SEX <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLike(String value) {
			addCriterion("SEX like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotLike(String value) {
			addCriterion("SEX not like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<String> values) {
			addCriterion("SEX in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<String> values) {
			addCriterion("SEX not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(String value1, String value2) {
			addCriterion("SEX between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(String value1, String value2) {
			addCriterion("SEX not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("BIRTHDAY is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("BIRTHDAY is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterion("BIRTHDAY =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterion("BIRTHDAY <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterion("BIRTHDAY >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterion("BIRTHDAY >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterion("BIRTHDAY <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterion("BIRTHDAY <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterion("BIRTHDAY in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterion("BIRTHDAY not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterion("BIRTHDAY between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterion("BIRTHDAY not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andDutyIsNull() {
			addCriterion("DUTY is null");
			return (Criteria) this;
		}

		public Criteria andDutyIsNotNull() {
			addCriterion("DUTY is not null");
			return (Criteria) this;
		}

		public Criteria andDutyEqualTo(String value) {
			addCriterion("DUTY =", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotEqualTo(String value) {
			addCriterion("DUTY <>", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyGreaterThan(String value) {
			addCriterion("DUTY >", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyGreaterThanOrEqualTo(String value) {
			addCriterion("DUTY >=", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyLessThan(String value) {
			addCriterion("DUTY <", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyLessThanOrEqualTo(String value) {
			addCriterion("DUTY <=", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyLike(String value) {
			addCriterion("DUTY like", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotLike(String value) {
			addCriterion("DUTY not like", value, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyIn(List<String> values) {
			addCriterion("DUTY in", values, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotIn(List<String> values) {
			addCriterion("DUTY not in", values, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyBetween(String value1, String value2) {
			addCriterion("DUTY between", value1, value2, "duty");
			return (Criteria) this;
		}

		public Criteria andDutyNotBetween(String value1, String value2) {
			addCriterion("DUTY not between", value1, value2, "duty");
			return (Criteria) this;
		}

		public Criteria andEnrolldateIsNull() {
			addCriterion("ENROLLDATE is null");
			return (Criteria) this;
		}

		public Criteria andEnrolldateIsNotNull() {
			addCriterion("ENROLLDATE is not null");
			return (Criteria) this;
		}

		public Criteria andEnrolldateEqualTo(Date value) {
			addCriterion("ENROLLDATE =", value, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateNotEqualTo(Date value) {
			addCriterion("ENROLLDATE <>", value, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateGreaterThan(Date value) {
			addCriterion("ENROLLDATE >", value, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateGreaterThanOrEqualTo(Date value) {
			addCriterion("ENROLLDATE >=", value, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateLessThan(Date value) {
			addCriterion("ENROLLDATE <", value, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateLessThanOrEqualTo(Date value) {
			addCriterion("ENROLLDATE <=", value, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateIn(List<Date> values) {
			addCriterion("ENROLLDATE in", values, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateNotIn(List<Date> values) {
			addCriterion("ENROLLDATE not in", values, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateBetween(Date value1, Date value2) {
			addCriterion("ENROLLDATE between", value1, value2, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEnrolldateNotBetween(Date value1, Date value2) {
			addCriterion("ENROLLDATE not between", value1, value2, "enrolldate");
			return (Criteria) this;
		}

		public Criteria andEducationIsNull() {
			addCriterion("EDUCATION is null");
			return (Criteria) this;
		}

		public Criteria andEducationIsNotNull() {
			addCriterion("EDUCATION is not null");
			return (Criteria) this;
		}

		public Criteria andEducationEqualTo(String value) {
			addCriterion("EDUCATION =", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationNotEqualTo(String value) {
			addCriterion("EDUCATION <>", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationGreaterThan(String value) {
			addCriterion("EDUCATION >", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationGreaterThanOrEqualTo(String value) {
			addCriterion("EDUCATION >=", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationLessThan(String value) {
			addCriterion("EDUCATION <", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationLessThanOrEqualTo(String value) {
			addCriterion("EDUCATION <=", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationLike(String value) {
			addCriterion("EDUCATION like", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationNotLike(String value) {
			addCriterion("EDUCATION not like", value, "education");
			return (Criteria) this;
		}

		public Criteria andEducationIn(List<String> values) {
			addCriterion("EDUCATION in", values, "education");
			return (Criteria) this;
		}

		public Criteria andEducationNotIn(List<String> values) {
			addCriterion("EDUCATION not in", values, "education");
			return (Criteria) this;
		}

		public Criteria andEducationBetween(String value1, String value2) {
			addCriterion("EDUCATION between", value1, value2, "education");
			return (Criteria) this;
		}

		public Criteria andEducationNotBetween(String value1, String value2) {
			addCriterion("EDUCATION not between", value1, value2, "education");
			return (Criteria) this;
		}

		public Criteria andMajorIsNull() {
			addCriterion("MAJOR is null");
			return (Criteria) this;
		}

		public Criteria andMajorIsNotNull() {
			addCriterion("MAJOR is not null");
			return (Criteria) this;
		}

		public Criteria andMajorEqualTo(String value) {
			addCriterion("MAJOR =", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotEqualTo(String value) {
			addCriterion("MAJOR <>", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThan(String value) {
			addCriterion("MAJOR >", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThanOrEqualTo(String value) {
			addCriterion("MAJOR >=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThan(String value) {
			addCriterion("MAJOR <", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThanOrEqualTo(String value) {
			addCriterion("MAJOR <=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLike(String value) {
			addCriterion("MAJOR like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotLike(String value) {
			addCriterion("MAJOR not like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorIn(List<String> values) {
			addCriterion("MAJOR in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotIn(List<String> values) {
			addCriterion("MAJOR not in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorBetween(String value1, String value2) {
			addCriterion("MAJOR between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotBetween(String value1, String value2) {
			addCriterion("MAJOR not between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andExperienceIsNull() {
			addCriterion("EXPERIENCE is null");
			return (Criteria) this;
		}

		public Criteria andExperienceIsNotNull() {
			addCriterion("EXPERIENCE is not null");
			return (Criteria) this;
		}

		public Criteria andExperienceEqualTo(String value) {
			addCriterion("EXPERIENCE =", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceNotEqualTo(String value) {
			addCriterion("EXPERIENCE <>", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceGreaterThan(String value) {
			addCriterion("EXPERIENCE >", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceGreaterThanOrEqualTo(String value) {
			addCriterion("EXPERIENCE >=", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceLessThan(String value) {
			addCriterion("EXPERIENCE <", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceLessThanOrEqualTo(String value) {
			addCriterion("EXPERIENCE <=", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceLike(String value) {
			addCriterion("EXPERIENCE like", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceNotLike(String value) {
			addCriterion("EXPERIENCE not like", value, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceIn(List<String> values) {
			addCriterion("EXPERIENCE in", values, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceNotIn(List<String> values) {
			addCriterion("EXPERIENCE not in", values, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceBetween(String value1, String value2) {
			addCriterion("EXPERIENCE between", value1, value2, "experience");
			return (Criteria) this;
		}

		public Criteria andExperienceNotBetween(String value1, String value2) {
			addCriterion("EXPERIENCE not between", value1, value2, "experience");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("ROLE_ID is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("ROLE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Integer value) {
			addCriterion("ROLE_ID =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Integer value) {
			addCriterion("ROLE_ID <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Integer value) {
			addCriterion("ROLE_ID >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ROLE_ID >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Integer value) {
			addCriterion("ROLE_ID <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
			addCriterion("ROLE_ID <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Integer> values) {
			addCriterion("ROLE_ID in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Integer> values) {
			addCriterion("ROLE_ID not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Integer value1, Integer value2) {
			addCriterion("ROLE_ID between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ROLE_ID not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("PARENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("PARENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdEqualTo(Integer value) {
			addCriterion("PARENT_ID =", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotEqualTo(Integer value) {
			addCriterion("PARENT_ID <>", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThan(Integer value) {
			addCriterion("PARENT_ID >", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PARENT_ID >=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThan(Integer value) {
			addCriterion("PARENT_ID <", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThanOrEqualTo(Integer value) {
			addCriterion("PARENT_ID <=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdIn(List<Integer> values) {
			addCriterion("PARENT_ID in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotIn(List<Integer> values) {
			addCriterion("PARENT_ID not in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdBetween(Integer value1, Integer value2) {
			addCriterion("PARENT_ID between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PARENT_ID not between", value1, value2, "parentId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_EMPLOYEE
	 * @mbggenerated  Mon Sep 04 23:11:35 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 04 14:21:27 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}