package com.entity;

public class TRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_ID
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_NAME
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_DESC
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    private String roleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_ID
     *
     * @return the value of T_ROLE.ROLE_ID
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_ID
     *
     * @param roleId the value for T_ROLE.ROLE_ID
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_NAME
     *
     * @return the value of T_ROLE.ROLE_NAME
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_ROLE.ROLE_NAME
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_DESC
     *
     * @return the value of T_ROLE.ROLE_DESC
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_DESC
     *
     * @param roleDesc the value for T_ROLE.ROLE_DESC
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }
}