package com.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.TASK_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     * 
     */
	private TEmployee implementor;
	private TEmployee assigner;
	private Integer planCount;
	
    public Integer getPlanCount() {
		return planCount;
	}

	public void setPlanCount(Integer planCount) {
		this.planCount = planCount;
	}

	public TEmployee getImplementor() {
		return implementor;
	}

	public void setImplementor(TEmployee implementor) {
		this.implementor = implementor;
	}

	public TEmployee getAssigner() {
		return assigner;
	}

	public void setAssigner(TEmployee assigner) {
		this.assigner = assigner;
	}

	private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.TASK_NAME
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.BEGIN_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.END_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.REAL_BEGIN_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date realBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.REAL_END_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date realEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.STATUS
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.IMPLEMENTOR_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    private Integer implementorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.ASSIGNER_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    private Integer assignerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.TASK_DESC
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    private String taskDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.TASK_ID
     *
     * @return the value of T_TASK.TASK_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.TASK_ID
     *
     * @param taskId the value for T_TASK.TASK_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.TASK_NAME
     *
     * @return the value of T_TASK.TASK_NAME
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.TASK_NAME
     *
     * @param taskName the value for T_TASK.TASK_NAME
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.BEGIN_DATE
     *
     * @return the value of T_TASK.BEGIN_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.BEGIN_DATE
     *
     * @param beginDate the value for T_TASK.BEGIN_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.END_DATE
     *
     * @return the value of T_TASK.END_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.END_DATE
     *
     * @param endDate the value for T_TASK.END_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.REAL_BEGIN_DATE
     *
     * @return the value of T_TASK.REAL_BEGIN_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public Date getRealBeginDate() {
        return realBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.REAL_BEGIN_DATE
     *
     * @param realBeginDate the value for T_TASK.REAL_BEGIN_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setRealBeginDate(Date realBeginDate) {
        this.realBeginDate = realBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.REAL_END_DATE
     *
     * @return the value of T_TASK.REAL_END_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public Date getRealEndDate() {
        return realEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.REAL_END_DATE
     *
     * @param realEndDate the value for T_TASK.REAL_END_DATE
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setRealEndDate(Date realEndDate) {
        this.realEndDate = realEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.STATUS
     *
     * @return the value of T_TASK.STATUS
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.STATUS
     *
     * @param status the value for T_TASK.STATUS
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.IMPLEMENTOR_ID
     *
     * @return the value of T_TASK.IMPLEMENTOR_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public Integer getImplementorId() {
        return implementorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.IMPLEMENTOR_ID
     *
     * @param implementorId the value for T_TASK.IMPLEMENTOR_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setImplementorId(Integer implementorId) {
        this.implementorId = implementorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.ASSIGNER_ID
     *
     * @return the value of T_TASK.ASSIGNER_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public Integer getAssignerId() {
        return assignerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.ASSIGNER_ID
     *
     * @param assignerId the value for T_TASK.ASSIGNER_ID
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setAssignerId(Integer assignerId) {
        this.assignerId = assignerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.TASK_DESC
     *
     * @return the value of T_TASK.TASK_DESC
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.TASK_DESC
     *
     * @param taskDesc the value for T_TASK.TASK_DESC
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc == null ? null : taskDesc.trim();
    }
}