package com.mapper;


import java.util.List;
import java.util.Map;

import com.entity.TEmployee;
import com.entity.TEmployeeExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface IEmployeeDao2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int countByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int deleteByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int deleteByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int insert(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int insertSelective(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    List<TEmployee> selectByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    TEmployee selectByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") TEmployee record, @Param("example") TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int updateByExample(@Param("record") TEmployee record, @Param("example") TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int updateByPrimaryKeySelective(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    int updateByPrimaryKey(TEmployee record);

    List<TEmployee> selectByPage(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Mon Sep 04 23:11:35 CST 2017
     */
    List<TEmployee> selectByPageExample(Map<String, Object> map);

    List<TEmployee> selectByPageExample1(Map<String, Object> map);

    List<TEmployee> selectByPageExample2(Map<String, Object> map);

    List<TEmployee> selectEmployees(Integer id);

}