package com.mapper;


import java.util.List;
import java.util.Map;

import com.entity.TPlan;
import com.entity.TPlanExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface IPlanDao2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int countByExample(TPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int deleteByExample(TPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int insert(TPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int insertSelective(TPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    List<TPlan> selectByExample(TPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    TPlan selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TPlan record, @Param("example") TPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByExample(@Param("record") TPlan record, @Param("example") TPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByPrimaryKeySelective(TPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PLAN
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByPrimaryKey(TPlan record);

    List<TPlan> selectByPage(Map<String, Object> map);

    List<TPlan> selectByPageExample(Map<String, Object> map);

    List<TPlan> selectByPageExample1(Map<String, Object> map);

}