package com.mapper;


import java.util.List;

import com.entity.TRole;
import com.entity.TRoleExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface IRoleDao2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int countByExample(TRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int deleteByExample(TRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int insert(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int insertSelective(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    List<TRole> selectByExample(TRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    TRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") TRole record, @Param("example") TRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int updateByExample(@Param("record") TRole record, @Param("example") TRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int updateByPrimaryKeySelective(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Mon Sep 04 23:19:53 CST 2017
     */
    int updateByPrimaryKey(TRole record);
}