package com.mapper;


import java.util.List;
import java.util.Map;

import com.entity.TTask;
import com.entity.TTaskExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ITaskDao2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int countByExample(TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int deleteByExample(TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int insert(TTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int insertSelective(TTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    List<TTask> selectByExample(TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    TTask selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TTask record, @Param("example") TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByExample(@Param("record") TTask record, @Param("example") TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByPrimaryKeySelective(TTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TASK
     *
     * @mbggenerated Thu Sep 07 13:33:54 CST 2017
     */
    int updateByPrimaryKey(TTask record);

    List<TTask> selectByPage(Map<String, Object> map);

    List<TTask> selectByPageExample(Map<String, Object> map);

    List<TTask> selectByPageExample1(Map<String, Object> map);

}